import { beforeEach, describe, expect, it, vi } from 'vitest';
const mocks = vi.hoisted(() => ({ open: vi.fn(), close: vi.fn(), session: vi.fn(), order: vi.fn(), history: vi.fn(), client: vi.fn(), rpc: vi.fn(), ticket: vi.fn(), tickets: vi.fn(), products: vi.fn() }));
vi.mock('@/app/pos/cash-actions', () => ({ openCashSessionAction: mocks.open, closeCashSessionAction: mocks.close }));
vi.mock('@/modules/cashflow/repository', () => ({ getOpenCashSession: mocks.session }));
vi.mock('@/modules/pos/order-repository', () => ({ getOrder: mocks.order, listOrdersHistory: mocks.history }));
vi.mock('@/server/integrations/supabase/server', () => ({ createSupabaseServerClient: mocks.client, createSupabaseServiceClient: async () => ({ rpc: mocks.rpc, from: () => { const query = { select: () => query, eq: () => query, order: () => query, limit: () => mocks.tickets(), maybeSingle: async () => { const result = await mocks.ticket(); return { ...result, data: result.data ? { id: result.data.id, label: result.data.label, cart_snapshot: result.data.cart, updated_at: result.data.updatedAt, created_at: result.data.createdAt, created_by_user_id: result.data.createdBy ?? "user" } : null }; } }; return query; } }) }));
vi.mock('@/modules/pos/saved-ticket-repository', () => ({ getSavedTicket: mocks.ticket, listSavedTickets: mocks.tickets }));
vi.mock('@/modules/catalog/repository', () => ({ listProducts: mocks.products }));
import { nativeWorkflow } from '@/modules/native-pos/workflow';
const scope = { storeId: '10000000-0000-4000-8000-000000000001', organizationId: 'org', userId: 'user', storeTimezone: 'Asia/Bangkok', canRecord: true };
const call = (operation: string, method = 'GET', body?: unknown, query = '') => nativeWorkflow(operation, method, new URL(`https://example.test/${query}`), body, scope);
beforeEach(() => { vi.clearAllMocks(); mocks.session.mockResolvedValue({ data: null, error: null }); mocks.history.mockResolvedValue({ data: [], error: null }); mocks.rpc.mockResolvedValue({ data: null, error: null }); });
describe('native cash and history workflow', () => {
  it('returns a missing session without inventing a cash amount', async () => { expect(await call('cash-session')).toMatchObject({ status: 200, body: { session: null, canRecord: true } }); });
  it('rejects fractional, negative and excessive money before mutation', async () => { for (const openingSatang of [-1, 0.5, 1000000001]) expect((await call('cash-open', 'POST', { openingSatang, note: '' }))?.status).toBe(400); expect(mocks.open).not.toHaveBeenCalled(); });
  it('denies cash mutation without record permission', async () => { expect((await nativeWorkflow('cash-open', 'POST', new URL('https://example.test'), { openingSatang: 0 }, { ...scope, canRecord: false }))?.status).toBe(403); expect(mocks.open).not.toHaveBeenCalled(); });
  it('fails on cash query errors instead of reporting zero', async () => { mocks.session.mockResolvedValue({ error: { userMessage: 'db error' }, data: null }); expect((await call('cash-session'))?.status).toBe(502); });
  it('fails on ledger errors instead of inventing expected cash', async () => { mocks.session.mockResolvedValue({ data: { id: scope.storeId, storeId: scope.storeId, organizationId: 'org', openingFloat: 100, openedAt: '2026-10-06T00:00:00Z' }, error: null }); const query = { select: () => query, eq: () => query, order: () => query, limit: () => query, lt: () => query, maybeSingle: async () => ({ error: { message: 'ledger failed' }, data: null }) }; mocks.client.mockResolvedValue({ from: () => query }); const result = await call('cash-session'); expect(result?.status).toBe(502); expect(result?.body).not.toHaveProperty('session'); });
  it('passes integer satang as baht to existing attendance and cash permission guarded actions', async () => { mocks.open.mockResolvedValue({ error: null }); expect((await call('cash-open', 'POST', { openingSatang: 12345, note: 'เปิดร้าน' }))?.status).toBe(200); expect(mocks.open).toHaveBeenCalledWith(123.45, 'เปิดร้าน'); mocks.close.mockResolvedValue({ error: null, session: { id: scope.storeId, storeId: scope.storeId, organizationId: 'org', status: 'closed', openingFloat: 100, openedAt: '2026-10-06T00:00:00Z', closingCount: 123.45, expectedCash: 120, variance: 3.45 } }); expect(await call('cash-close', 'POST', { sessionId: scope.storeId, closingSatang: 12345 })).toMatchObject({ status: 200, body: { session: { closingSatang: 12345, expectedSatang: 12000, varianceSatang: 345 } } }); expect(mocks.close).toHaveBeenCalledWith(scope.storeId, 123.45, undefined); });
  it('enforces calendar dates and inclusive 31 day maximum', async () => { for (const query of ['?fromDate=2026-02-30&toDate=2026-03-01', '?fromDate=2026-01-01&toDate=2026-02-01', '?fromDate=2026-02-01&toDate=2026-01-01']) expect((await call('history', 'GET', undefined, query))?.status).toBe(400); expect(mocks.history).not.toHaveBeenCalled(); expect((await call('history', 'GET', undefined, '?fromDate=2026-01-01&toDate=2026-01-31'))?.status).toBe(200); expect(mocks.history).toHaveBeenCalledWith(scope.storeId, 'Asia/Bangkok', { fromDate: '2026-01-01', toDate: '2026-01-31', limit: 100 }); });
  it('rejects an order from a different store or organization', async () => { for (const data of [{ storeId: 'other', organizationId: 'org' }, { storeId: scope.storeId, organizationId: 'other' }]) { mocks.order.mockResolvedValue({ data, error: null }); expect((await call('order-detail', 'GET', undefined, `?id=${scope.storeId}`))?.status).toBe(404); } });
});
const ticketId = '20000000-0000-4000-8000-000000000002', claimId = '30000000-0000-4000-8000-000000000003', updatedAt = '2026-10-06T02:00:00.000Z';
const resume = { id: ticketId, claimId, updatedAt };
const ticket = { id: ticketId, label: 'พัก', updatedAt, createdAt: updatedAt, cart: { storeId: scope.storeId, subtotal: 65, total: 65, discount: 0, items: [{ key: 'key', productId: ticketId, productName: 'กาแฟ', variant: null, modifiers: [], quantity: 1, unitPrice: 65, totalPrice: 65 }] } };
describe('native ticket safety', () => {
  it('recovers a committed immutable save without using changed catalog prices', async () => { mocks.ticket.mockResolvedValue({ data: ticket, error: null }); const payload = { id: ticketId, label: 'พัก', expectedTotalSatang: 6500, lines: [{ key: 'key', productId: ticketId, name: 'กาแฟ', quantity: 1, unitSatang: 6500, variantId: null, optionIds: [], note: '' }] }; expect(await call('ticket-save', 'POST', payload)).toMatchObject({ status: 200, body: { ticket: { id: ticketId, updatedAt } } }); expect(mocks.products).not.toHaveBeenCalled(); expect(mocks.rpc).not.toHaveBeenCalled(); expect((await call('ticket-save', 'POST', { ...payload, label: 'changed' }))?.status).toBe(409); });
  it('rejects invalid parked money before any lookup or write', async () => { expect((await call('ticket-save', 'POST', { id: ticketId, label: 'พัก', lines: [], expectedTotalSatang: -1 }))?.status).toBe(400); expect(mocks.ticket).not.toHaveBeenCalled(); expect(mocks.rpc).not.toHaveBeenCalled(); });
  it('recovers a prior claim before touching the deleted source ticket', async () => { const result = { id: ticketId, label: 'พัก', lines: [], checkoutOperationId: claimId }; mocks.rpc.mockResolvedValue({ data: result, error: null }); expect(await call('ticket-resume', 'POST', resume)).toMatchObject({ status: 200, body: result }); expect(mocks.ticket).not.toHaveBeenCalled(); });
  it('does not fall back to destructive get/delete when migration is unavailable', async () => { mocks.rpc.mockResolvedValue({ data: null, error: { code: 'PGRST202' } }); expect((await call('ticket-resume', 'POST', resume))?.status).toBe(503); expect(mocks.ticket).not.toHaveBeenCalled(); });
  it('rejects stale and cross-store source snapshots without claiming', async () => { for (const data of [{ ...ticket, updatedAt: '2026-10-06T03:00:00Z' }, { ...ticket, cart: { ...ticket.cart, storeId: 'other' } }]) { mocks.rpc.mockClear(); mocks.ticket.mockResolvedValue({ data, error: null }); expect((await call('ticket-resume', 'POST', resume))?.status).toBeGreaterThanOrEqual(400); expect(mocks.rpc).toHaveBeenCalledTimes(1); } });
  it('rejects table, discount, reward and unit information without losing it', async () => { for (const data of [{ ...ticket, cart: { ...ticket.cart, discount: 1 } }, { ...ticket, cart: { ...ticket.cart, items: [{ ...ticket.cart.items[0], rewardVoucherCode: 'reward' }] } }, { ...ticket, cart: { ...ticket.cart, items: [{ ...ticket.cart.items[0], unit: { id: ticketId } }] } }]) { mocks.rpc.mockClear(); mocks.ticket.mockResolvedValue({ data, error: null }); expect((await call('ticket-resume', 'POST', resume))?.status).toBe(409); expect(mocks.rpc).toHaveBeenCalledTimes(1); } });
  it('preserves the source ticket on data failures', async () => { mocks.ticket.mockResolvedValue({ data: null, error: { userMessage: 'failed' } }); expect((await call('ticket-resume', 'POST', resume))?.status).toBe(502); expect(mocks.rpc).toHaveBeenCalledTimes(1); });
  it('rechecks catalog pricing before consuming and passes immutable source snapshot', async () => { mocks.ticket.mockResolvedValue({ data: ticket, error: null }); const product = { id: ticketId, storeId: scope.storeId, name: 'กาแฟ', categoryId: 'c', basePrice: 65, isActive: true, availableForPos: true, variants: [], modifierGroups: [] }; mocks.products.mockResolvedValue({ data: [product], error: null }); const result = { id: ticketId, checkoutOperationId: claimId }; mocks.rpc.mockResolvedValueOnce({ data: null, error: null }).mockResolvedValueOnce({ data: result, error: null }); expect((await call('ticket-resume', 'POST', resume))?.body).toEqual(result); expect(mocks.rpc).toHaveBeenLastCalledWith('native_pos_claim_ticket', expect.objectContaining({ p_expected_cart: ticket.cart, p_claim_id: claimId, p_result: expect.objectContaining({ checkoutOperationId: claimId }) })); mocks.rpc.mockClear(); mocks.products.mockResolvedValue({ data: [{ ...product, basePrice: 66 }], error: null }); expect((await call('ticket-resume', 'POST', resume))?.status).toBe(409); expect(mocks.rpc).toHaveBeenCalledTimes(1); });
});


